//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWepAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdcsurvey
    {
        public System.Guid id { get; set; }
        public string variable { get; set; }
        public string question { get; set; }
        public string survey { get; set; }
        public Nullable<long> year { get; set; }
        public string timing { get; set; }
        public string key1 { get; set; }
        public string key2 { get; set; }
        public string key3 { get; set; }
        public string client { get; set; }
        public string superset { get; set; }
    }
}
